name = "www"
type = "webpack"
workers_dev = true
account_id = "3318ec21330ab3808c1a9ce3470d263b"
zone_id = "e15a47e69e4f029ecdcbeb684bddbb31"
kv_namespaces = [
    { binding = "BUCKET", id = "7599512ae12b4a2090be630cc1f71649" }
]

[env.staging]
name = "drive-staging"
